[package]
name = "diffz-todo-annotator"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.62", default-features = false, features = ["macros", "realloc"] }

[profile.release]
opt-level = "s"
lto = true
strip = true

[workspace]
